package apresentacao;

import comanda.Pedido;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class Tela extends javax.swing.JFrame {
    
    String conta;
    double subtotal;
    double valorT;
    double gorjeta;
    
    double valedesconto;
   
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prato1 = new javax.swing.JCheckBox();
        prato2 = new javax.swing.JCheckBox();
        prato3 = new javax.swing.JCheckBox();
        prato4 = new javax.swing.JCheckBox();
        prato5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtdrefri = new javax.swing.JSpinner();
        qtdsuco = new javax.swing.JSpinner();
        qtdcerveja = new javax.swing.JSpinner();
        qtdagua = new javax.swing.JSpinner();
        alface = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tomate = new javax.swing.JCheckBox();
        cebola = new javax.swing.JCheckBox();
        cenoura = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        sorvete = new javax.swing.JCheckBox();
        pudim = new javax.swing.JCheckBox();
        torta = new javax.swing.JCheckBox();
        sagu = new javax.swing.JCheckBox();
        desconto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        taxa = new javax.swing.JCheckBox();
        calculo = new javax.swing.JButton();
        fecharC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prato1.setText("Filé ao molho Madeira");
        prato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prato1ActionPerformed(evt);
            }
        });

        prato2.setText("Filé Grelhado");
        prato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prato2ActionPerformed(evt);
            }
        });

        prato3.setText("Filé de Salmão Grelhado");
        prato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prato3ActionPerformed(evt);
            }
        });

        prato4.setText("Bistecas Suínas Defumadas e Grelhada");
        prato4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prato4ActionPerformed(evt);
            }
        });

        prato5.setText("Peito de Frango Grelhado");
        prato5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prato5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Prato Execdutivo");

        jLabel2.setText("Bebidas");

        alface.setText("alface ");
        alface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfaceActionPerformed(evt);
            }
        });

        jLabel3.setText("Saladas");

        tomate.setText("tomate ");
        tomate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomateActionPerformed(evt);
            }
        });

        cebola.setText("cebola ");
        cebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cebolaActionPerformed(evt);
            }
        });

        cenoura.setText("cenoura");
        cenoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenouraActionPerformed(evt);
            }
        });

        jLabel4.setText("Sobremesas");

        sorvete.setText("Sorvete");
        sorvete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorveteActionPerformed(evt);
            }
        });

        pudim.setText("Pudim");
        pudim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pudimActionPerformed(evt);
            }
        });

        torta.setText("Torta");
        torta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tortaActionPerformed(evt);
            }
        });

        sagu.setText("Sagu");
        sagu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saguActionPerformed(evt);
            }
        });

        desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descontoActionPerformed(evt);
            }
        });

        jLabel5.setText("Desconto:");

        taxa.setText("Taxa de Serviço (10%)");
        taxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaActionPerformed(evt);
            }
        });

        calculo.setText("Calcular");
        calculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculoActionPerformed(evt);
            }
        });

        fecharC.setText("Fechar Conta");
        fecharC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharCActionPerformed(evt);
            }
        });

        jLabel6.setText("Extrato:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setText("refrigerante 350ml");

        jLabel8.setText("suco natural 400ml");

        jLabel9.setText("cerveja 350ml");

        jLabel10.setText("agua 500ml");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(prato5)
                                    .addComponent(prato4)
                                    .addComponent(prato3)
                                    .addComponent(prato2)
                                    .addComponent(prato1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(qtdsuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtdcerveja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtdrefri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(calculo)
                                                .addGap(20, 20, 20))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(taxa)))))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fecharC)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(alface)
                                        .addComponent(tomate)
                                        .addComponent(cebola)
                                        .addComponent(cenoura)
                                        .addComponent(sorvete)
                                        .addComponent(pudim)
                                        .addComponent(torta)
                                        .addComponent(sagu))
                                    .addGap(55, 55, 55)))))
                    .addComponent(jLabel6))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prato1)
                    .addComponent(alface))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prato2)
                    .addComponent(tomate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prato3)
                    .addComponent(cebola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prato4)
                    .addComponent(cenoura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prato5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdrefri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorvete)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdsuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pudim)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdcerveja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torta)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sagu)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharC)
                    .addComponent(calculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prato2ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_prato2ActionPerformed

    private void prato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prato3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prato3ActionPerformed

    private void prato4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prato4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prato4ActionPerformed

    private void prato5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prato5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prato5ActionPerformed

    private void alfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alfaceActionPerformed

    private void tomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomateActionPerformed

    private void cebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cebolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cebolaActionPerformed

    private void cenouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenouraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cenouraActionPerformed

    
    private void descontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descontoActionPerformed

    private void taxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaActionPerformed

    private void calculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculoActionPerformed
                 addprato();   
                 addsalada();                 
                 addbebida();
                 addsobremesa();
                 addgorjeta();
                 adddesconto();
                 valorT =+ subtotal;        // TODO add your handling code here:
      
                  jTextArea1.setText(conta+"\n"+"subtotal:............. R$ "+subtotal+"\n"+"Valor de gorjeta......... R$"+gorjeta+"\n"+" Valor de desconto.......... R$ "+valedesconto+" \n"+"Valor total............. R$ "+valorT);
               
           setRegistro(conta+"\nsubtotal:............. R$ "+subtotal+"\n"+"Valor de gorjeta......... R$"+gorjeta+"\n"+ "Valor de desconto.......... R$ "+valedesconto+"\nValor total............. R$ "+valorT); 
           
                System.out.println(getRegistro());
             
            Pedido.inserir();
              
                subtotal=0;
                valorT=0;
                gorjeta=0;
                valedesconto = 0;
                setRegistro("");
                conta="";
                 
    }//GEN-LAST:event_calculoActionPerformed

    private void fecharCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharCActionPerformed
    this.jTextArea1setText ("         ");
// TODO add your handling code here:
    }//GEN-LAST:event_fecharCActionPerformed

    private void saguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saguActionPerformed

    private void tortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tortaActionPerformed

    private void pudimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pudimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pudimActionPerformed

    private void sorveteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorveteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sorveteActionPerformed

    private void prato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prato1ActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_prato1ActionPerformed

    
    
     public void addprato(){
         
        
        if(prato1.isSelected()){
            
           conta = ("Filé ao Molho Madeira"+"             " +"R$ 23,00");
           subtotal=(float) +23.00;
            
        }
        if(prato2.isSelected()){
            conta = ("Filé Grelhado"+"                     " +"R$ 19,00");
            subtotal=(float) +19.00;
        }
        if(prato3.isSelected()){
         conta =("Filé de Salmão Grelhado"+"                " +"R$ 25,00");
         subtotal=(float) +25.00;
           
                    
        }
        if(prato4.isSelected()){
           conta = ("Bistecas Suınas D/G"+"                  " +"R$ 22,00");
             subtotal=(float) +22.00;
        }
        if(prato5.isSelected()){
         conta =("Peito de Frango Grelhado"+"                " +"R$ 18,00");
            subtotal=(float) +18.00;
         }
    
}
  public void addsalada(){
       if(alface.isSelected()){
         conta=(conta+"\n"+"Alface                                R$ 1,00");
          subtotal=(float)subtotal+1;
           
       }
       if(tomate.isSelected()){
         conta=(conta+"\n"+"Tomate                                R$ 1,00");
          subtotal=(float)subtotal+1;
           
       }
       if(cebola.isSelected()){
         conta=(conta+"\n"+"Cebola                                R$ 1,00");
          subtotal=(float)subtotal+1;
           
       }
       if(cenoura.isSelected()){
         conta=(conta+"\n"+"Cenoura                               R$ 1,00");
          subtotal=(float)subtotal+1;
           
       }
    }
  
  public void addbebida(){
        int quant=0;
        quant=Integer.parseInt(qtdagua.getValue().toString());
        if(quant>0){
            conta=(conta+"\n"+"Agua....................R$ 2,50 X"+quant+"Un");
            subtotal=(float) ((float)subtotal+2.5*(quant));
            quant=0;
        }
        quant=Integer.parseInt(qtdcerveja.getValue().toString());
        if(quant>0){
            conta=(conta+"\n"+"Cerveja...............R$ 5,00 X"+quant+"Un");
            subtotal=(float) ((float)subtotal+5.0*(quant));
            quant=0;
        }
        quant=Integer.parseInt(qtdsuco.getValue().toString());
        if(quant>0){
            conta=(conta+"\n"+"Suco Natural...............R$ 4,00 X"+quant+"Un");
            subtotal=(float) ((float)subtotal+4.0*(quant));
            quant=0;
        }
        quant=Integer.parseInt(qtdrefri.getValue().toString());
        if(quant>0){
            conta=(conta+"\n"+"Refrigerante...............R$ 3,00 X"+quant+"Un");
            subtotal=(float) ((float)subtotal+(3.0*quant));
            quant=0;
        }
    }
  
  public void addsobremesa(){
       
       if(sorvete.isSelected()){
         conta=(conta+"\n"+"sorvete                              R$ 4,00");
          subtotal=(float)subtotal+1;
           
       }
       if(pudim.isSelected()){
         conta=(conta+"\n"+"pudim                                R$ 5,00");
          subtotal=(float)subtotal+1;
           
       }
       if(torta.isSelected()){
         conta=(conta+"\n"+"torta                                R$ 6,00");
          subtotal=(float)subtotal+1;
           
       }
       if(sagu.isSelected()){
         conta=(conta+"\n"+"sagu                                 R$ 4,50");
          subtotal=(float)subtotal+1;
           
       }
    }
    
  public void addgorjeta(){
        if(taxa.isSelected()){
          gorjeta = (float)(subtotal*0.1);  
          valorT = ((float)(valorT+gorjeta));
        }
    }
  
  public void adddesconto(){
        int valdesc;
        valdesc = Integer.parseInt(desconto.getText().toString());
        valedesconto=valedesconto*valorT/100;
        valorT=valorT-valedesconto;
  }
  
                 
                 /**            
     * @param args the command line arguments
     * }
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alface;
    private javax.swing.JButton calculo;
    private javax.swing.JCheckBox cebola;
    private javax.swing.JCheckBox cenoura;
    private javax.swing.JTextField desconto;
    private javax.swing.JButton fecharC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox prato1;
    private javax.swing.JCheckBox prato2;
    private javax.swing.JCheckBox prato3;
    private javax.swing.JCheckBox prato4;
    private javax.swing.JCheckBox prato5;
    private javax.swing.JCheckBox pudim;
    private javax.swing.JSpinner qtdagua;
    private javax.swing.JSpinner qtdcerveja;
    private javax.swing.JSpinner qtdrefri;
    private javax.swing.JSpinner qtdsuco;
    private javax.swing.JCheckBox sagu;
    private javax.swing.JCheckBox sorvete;
    private javax.swing.JCheckBox taxa;
    private javax.swing.JCheckBox tomate;
    private javax.swing.JCheckBox torta;
    // End of variables declaration//GEN-END:variables

    public String getRegistro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setRegistro(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void jTextArea1setText(String _________) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
