/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Ticket;
import database.TicketDAO;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.SpinnerNumberModel;


/**
 *
 * @author Lucas
 */
public class TelaComanda extends javax.swing.JFrame {

    /**
     * Creates new form TelaComanda
     */
    public TelaComanda() {
        initComponents();
    }
    Ticket cupom = new Ticket();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPratoPrincipal = new javax.swing.JPanel();
        jCheckBoxFileMM = new javax.swing.JCheckBox();
        jCheckBoxFileG = new javax.swing.JCheckBox();
        jCheckBoxFileSG = new javax.swing.JCheckBox();
        jCheckBoxBisteca = new javax.swing.JCheckBox();
        jCheckBoxPeito = new javax.swing.JCheckBox();
        jLabelPratoPrincipal = new javax.swing.JLabel();
        jPanelSaladas = new javax.swing.JPanel();
        jLabelSaladas = new javax.swing.JLabel();
        jCheckBoxCenoura = new javax.swing.JCheckBox();
        jCheckBoxCebola = new javax.swing.JCheckBox();
        jCheckBoxTomate = new javax.swing.JCheckBox();
        jCheckBoxAlface = new javax.swing.JCheckBox();
        jPanelBebidas = new javax.swing.JPanel();
        jLabelBebidas = new javax.swing.JLabel();
        SpinnerCerveja = new javax.swing.JSpinner();
        SpinnerSuco = new javax.swing.JSpinner();
        SpinnerAgua = new javax.swing.JSpinner();
        SpinnerRefri = new javax.swing.JSpinner();
        jLabelCerveja = new javax.swing.JLabel();
        jLabelSuco = new javax.swing.JLabel();
        jLabelAgua = new javax.swing.JLabel();
        jLabelRefri = new javax.swing.JLabel();
        combosobremesa = new javax.swing.JComboBox<>();
        jLabelSobremesa = new javax.swing.JLabel();
        jTextFieldDesconto = new javax.swing.JTextField();
        jLabelDesconto = new javax.swing.JLabel();
        jCheckBoxTxServico = new javax.swing.JCheckBox();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();
        jScrollPaneTicket = new javax.swing.JScrollPane();
        jTextAreaTicket = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPratoPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jPanelPratoPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jCheckBoxFileMM.setText("Filé ao Molho Madeira");

        jCheckBoxFileG.setText("Filé Grelhado");

        jCheckBoxFileSG.setText("Filé de Salmão Grelhado");

        jCheckBoxBisteca.setText("Bistecas Suínas Defumadas e Grelhadas");

        jCheckBoxPeito.setText("Peito de Frango Grelhado");

        jLabelPratoPrincipal.setText("Prato Principal");

        javax.swing.GroupLayout jPanelPratoPrincipalLayout = new javax.swing.GroupLayout(jPanelPratoPrincipal);
        jPanelPratoPrincipal.setLayout(jPanelPratoPrincipalLayout);
        jPanelPratoPrincipalLayout.setHorizontalGroup(
            jPanelPratoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPratoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPratoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxFileMM)
                    .addComponent(jCheckBoxFileG)
                    .addComponent(jCheckBoxFileSG)
                    .addComponent(jCheckBoxBisteca)
                    .addComponent(jCheckBoxPeito)
                    .addComponent(jLabelPratoPrincipal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPratoPrincipalLayout.setVerticalGroup(
            jPanelPratoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPratoPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPratoPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFileMM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxFileG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxFileSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxBisteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxPeito)
                .addContainerGap())
        );

        jPanelSaladas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabelSaladas.setText("Saladas");

        jCheckBoxCenoura.setText("Cenoura");

        jCheckBoxCebola.setText("Cebola");

        jCheckBoxTomate.setText("Tomate");

        jCheckBoxAlface.setText("Alface");

        javax.swing.GroupLayout jPanelSaladasLayout = new javax.swing.GroupLayout(jPanelSaladas);
        jPanelSaladas.setLayout(jPanelSaladasLayout);
        jPanelSaladasLayout.setHorizontalGroup(
            jPanelSaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaladasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaladas)
                    .addGroup(jPanelSaladasLayout.createSequentialGroup()
                        .addGroup(jPanelSaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCenoura)
                            .addComponent(jCheckBoxCebola))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxAlface)
                            .addComponent(jCheckBoxTomate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSaladasLayout.setVerticalGroup(
            jPanelSaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaladasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSaladas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCenoura)
                    .addComponent(jCheckBoxTomate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSaladasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCebola)
                    .addComponent(jCheckBoxAlface))
                .addContainerGap())
        );

        jPanelBebidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabelBebidas.setText("Bebidas");

        SpinnerCerveja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpinnerCerveja.setOpaque(false);
        SpinnerCerveja.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerCervejaStateChanged(evt);
            }
        });

        SpinnerSuco.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpinnerSuco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerSucoStateChanged(evt);
            }
        });

        SpinnerAgua.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpinnerAgua.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerAguaStateChanged(evt);
            }
        });

        SpinnerRefri.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SpinnerRefri.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerRefriStateChanged(evt);
            }
        });

        jLabelCerveja.setText("Cerveja");

        jLabelSuco.setText("Suco");

        jLabelAgua.setText("Água");

        jLabelRefri.setText("Refrigerante");

        javax.swing.GroupLayout jPanelBebidasLayout = new javax.swing.GroupLayout(jPanelBebidas);
        jPanelBebidas.setLayout(jPanelBebidasLayout);
        jPanelBebidasLayout.setHorizontalGroup(
            jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SpinnerSuco)
                    .addComponent(SpinnerCerveja)
                    .addComponent(jLabelBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCerveja)
                    .addComponent(jLabelSuco))
                .addGap(18, 18, 18)
                .addGroup(jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SpinnerAgua, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(SpinnerRefri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAgua)
                    .addComponent(jLabelRefri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBebidasLayout.setVerticalGroup(
            jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBebidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerCerveja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCerveja)
                    .addComponent(jLabelAgua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerSuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerRefri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSuco)
                    .addComponent(jLabelRefri))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        combosobremesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "               ", "Sorvete", "Pudim", "Torta", "Sagu" }));
        combosobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosobremesaActionPerformed(evt);
            }
        });

        jLabelSobremesa.setText("Sobremesas");

        jTextFieldDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescontoFocusLost(evt);
            }
        });

        jLabelDesconto.setText("Desconto");

        jCheckBoxTxServico.setText("Taxa de serviço");
        jCheckBoxTxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxTxServicoItemStateChanged(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jTextAreaTicket.setColumns(20);
        jTextAreaTicket.setRows(5);
        jScrollPaneTicket.setViewportView(jTextAreaTicket);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSobremesa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxTxServico)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDesconto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addGap(13, 13, 13))
                            .addComponent(combosobremesa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPratoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSaladas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBebidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPratoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelSaladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneTicket))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDesconto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTxServico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCalcular, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSobremesa)
                        .addGap(7, 7, 7)
                        .addComponent(combosobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        List<JCheckBox> pratoprincipal = new ArrayList<>();
        List<JCheckBox> saladas = new ArrayList<>();
        List<String> info = new ArrayList<>();
        for( Component comp : jPanelPratoPrincipal.getComponents() ) {
            if( comp instanceof JCheckBox) pratoprincipal.add( (JCheckBox)comp );
        }
        for( Component comp : jPanelSaladas.getComponents() ) {
            if( comp instanceof JCheckBox) saladas.add( (JCheckBox)comp );
        }

        for(JCheckBox boxpp : pratoprincipal){
            if(boxpp.isSelected()){
                info.add(boxpp.getText());
            }
        }
        for(JCheckBox boxsa : saladas){
            if(boxsa.isSelected()){
                info.add(boxsa.getText());
           }
        }
        cupom.ContaComida(info);
        cupom.ContaTudo();
        jTextAreaTicket.setText(cupom.Escreve());
        System.out.println(jTextAreaTicket.getText());
        try {
            new TicketDAO().inserir(jTextAreaTicket.getText().replace("\n", "|"));
        } catch (SQLException ex) {
            Logger.getLogger(TelaComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void SpinnerCervejaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerCervejaStateChanged
        cupom.ContaCerveja(SpinnerCerveja.getValue());
    }//GEN-LAST:event_SpinnerCervejaStateChanged

    private void SpinnerSucoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerSucoStateChanged
        cupom.ContaSuco(SpinnerSuco.getValue());
    }//GEN-LAST:event_SpinnerSucoStateChanged

    private void SpinnerAguaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerAguaStateChanged
       cupom.ContaAgua(SpinnerAgua.getValue());
    }//GEN-LAST:event_SpinnerAguaStateChanged

    private void SpinnerRefriStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerRefriStateChanged
        cupom.ContaRefri(SpinnerRefri.getValue());
    }//GEN-LAST:event_SpinnerRefriStateChanged

    private void combosobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosobremesaActionPerformed
        cupom.Sobremesa(combosobremesa.getSelectedItem());
    }//GEN-LAST:event_combosobremesaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        List<JCheckBox> pratoprincipal = new ArrayList<>();
        List<JCheckBox> saladas = new ArrayList<>();
        for( Component comp : jPanelPratoPrincipal.getComponents() ) {
            if( comp instanceof JCheckBox) pratoprincipal.add( (JCheckBox)comp );
        }
        for( Component comp : jPanelSaladas.getComponents() ) {
            if( comp instanceof JCheckBox) saladas.add( (JCheckBox)comp );
        }
        for(JCheckBox boxpp : pratoprincipal){
            if(boxpp.isSelected()){
                boxpp.setSelected(false);
            }
        }
        for(JCheckBox boxsa : saladas){
            if(boxsa.isSelected()){
                boxsa.setSelected(false);
           }
        }
        combosobremesa.setSelectedIndex(0);
        jCheckBoxTxServico.setSelected(false);
        jTextFieldDesconto.setText("0");
        jTextAreaTicket.setText("");
        SpinnerAgua.setValue(((SpinnerNumberModel) SpinnerAgua.getModel()).getMinimum());
        SpinnerCerveja.setValue(((SpinnerNumberModel) SpinnerCerveja.getModel()).getMinimum());
        SpinnerRefri.setValue(((SpinnerNumberModel) SpinnerRefri.getModel()).getMinimum());
        SpinnerSuco.setValue(((SpinnerNumberModel) SpinnerSuco.getModel()).getMinimum());
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescontoFocusLost
       cupom.ValidaNumero(jTextFieldDesconto.getText());
    }//GEN-LAST:event_jTextFieldDescontoFocusLost

    private void jCheckBoxTxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxTxServicoItemStateChanged
        if(jCheckBoxTxServico.isSelected()){
            cupom.addTxServico();
        }else{
            cupom.remTXservico();
        }
    }//GEN-LAST:event_jCheckBoxTxServicoItemStateChanged
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerAgua;
    private javax.swing.JSpinner SpinnerCerveja;
    private javax.swing.JSpinner SpinnerRefri;
    private javax.swing.JSpinner SpinnerSuco;
    private javax.swing.JComboBox<String> combosobremesa;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxAlface;
    private javax.swing.JCheckBox jCheckBoxBisteca;
    private javax.swing.JCheckBox jCheckBoxCebola;
    private javax.swing.JCheckBox jCheckBoxCenoura;
    private javax.swing.JCheckBox jCheckBoxFileG;
    private javax.swing.JCheckBox jCheckBoxFileMM;
    private javax.swing.JCheckBox jCheckBoxFileSG;
    private javax.swing.JCheckBox jCheckBoxPeito;
    private javax.swing.JCheckBox jCheckBoxTomate;
    private javax.swing.JCheckBox jCheckBoxTxServico;
    private javax.swing.JLabel jLabelAgua;
    private javax.swing.JLabel jLabelBebidas;
    private javax.swing.JLabel jLabelCerveja;
    private javax.swing.JLabel jLabelDesconto;
    private javax.swing.JLabel jLabelPratoPrincipal;
    private javax.swing.JLabel jLabelRefri;
    private javax.swing.JLabel jLabelSaladas;
    private javax.swing.JLabel jLabelSobremesa;
    private javax.swing.JLabel jLabelSuco;
    private javax.swing.JPanel jPanelBebidas;
    private javax.swing.JPanel jPanelPratoPrincipal;
    private javax.swing.JPanel jPanelSaladas;
    private javax.swing.JScrollPane jScrollPaneTicket;
    private javax.swing.JTextArea jTextAreaTicket;
    private javax.swing.JTextField jTextFieldDesconto;
    // End of variables declaration//GEN-END:variables
}
